sudo: required
services:
- docker
language: bash
script:
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    # prepare environment
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

    echo "============"
    git diff --name-only $TRAVIS_COMMIT_RANGE
    echo "============"
    git diff --name-only HEAD...$TRAVIS_BRANCH
    echo "============"
    git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH

    # get changed images
    IMAGES=($(git diff --name-only $TRAVIS_COMMIT_RANGE | grep images/))

    # build/tag/push images
    cd images
    for IMAGE in "${IMAGES[@]}"
    do
      IMAGE_PATH=$(echo $IMAGE | tr "/" "\n")
      IMAGE_NAME=${IMAGE_PATH[1]}
      PLATFORM=${IMAGE_PATH[2]}
      TAG=echo $TRAVIS_BRANCH | sed -n -e 's/[^\.]+\.(.*)/\1/p'
      if [ -z $TAG ]; then
        TAG="latest"
      fi
      echo "============"
      echo $IMAGE_NAME
      echo $PLATFORM
      echo $TAG
      echo "============"
      # ./build.sh $IMAGE_NAME $PLATFORM
      # ./tag.sh $IMAGE_NAME $TAG $PLATFORM
      # ./push.sh $IMAGE_NAME $TAG $PLATFORM
    done
  fi